[project]
name = "memalloc-bench"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "altair>=6.0.0",
    "pandas>=2.3.3",
    "polars>=1.35.2",
    "pyarrow>=22.0.0",
    "vl-convert-python>=1.8.0",
]
